import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <div className="absolute w-full z-10">
          <div className="flex justify-between container mx-auto text-white p-8">
            <Link className="text-3xl font-bold" href="/">Home</Link>
            <div className="text-xl space-x-4">
              <Link href="/performance">performance</Link>
              <Link href="/reliability">reliability</Link>
              <Link href="/scale">scale</Link>
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
